
<footer>
<h2> Made by Alex </h2>
<h2> &copy; 2019 </h2>
</footer>
</center>
<table style="background-color: #000000; color: #ffffff; width: 100%;" border=1>
<tr>
<td>

<h1>List Variables</h1>
[listvariables]
[index].) [name] = "[value]"<br> 
[/listvariables]
</td>
<td>
<h1>Form Variable</h1>
[Formvariables]
[index].) [name] = "[value]"<br>
[/Formvariables]
</td>
<td>
<h1>List Cookies</h1>
[listcookies]
[index].) [name] = "[value]"<br>
[/listcookies]
</td>
<td>
<h1>List Mimeheaders</h1>
[listmimeheaders]
[index].) [name] = "[value]"<br>
[/listmimeheaders]
</td>
<td>
</table>
