<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
}

<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ff8c00;
  color: black;
}

.topnav a.active {
  background-color: #4CAF50;
  color: white;
}
.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 16px;  
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.navbar a:hover, .dropdown:hover .dropbtn {
  background-color: red;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {
  background-color: #ddd;
}

.dropdown:hover .dropdown-content {
  display: block;
}
</style>
</head>
<body>
</style>
<link rel="stylesheet" href="/citi/coding/2020/ad/llf/css/style.css">

</head>
<body>

<div class="topnav">
  <a class="active" href="/citi/coding/2020/ad/llf/index.html">Home</a>
  <a href="/citi/coding/2020/ad/llf/aboutus/index.html">About</a>
  <a href="/citi/coding/2020/ad/llf/gallery/index.html">Gallery</a>
  <a href="/citi/coding/2020/ad/llf/blog/index.html">Blog</a>
  <a href="/citi/coding/2020/ad/llf/login/index.html">Login/Signup</a>
  <a href="/citi/coding/2020/ad/llf/contact/index.html">Contact</a>
<div class="dropdown">
    <button class="dropbtn">Admins 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="/citi/coding/2020/ad/llf/20admin20/states/index.html">States</a>
      <a href="/citi/coding/2020/ad/llf/20admin20/category/index.html">Category</a>
      <a href="/citi/coding/2020/ad/llf/20admin20/country/index.html">Country</a>
      <a href="/citi/coding/2020/ad/llf/20admin20/gallery/index.html">Gallery</a>
      </div>
  </div> 
</div>


</div>

<div style="padding-left:16px">
 
</div>

</body>
</html>
